### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by prasadkamble0062** [imsaksham-c/Fire-Smoke-Detection#1]
In training. Ipynb

Last prediction code i am getting assertion error please will u help me to resolved that error.

**Comment by imsaksham-c** [comment]
Can you attach the file/screenshot so that I can go through the details

**Comment by prasadkamble0062** [comment]
doc has error ss

**Comment by imsaksham-c** [comment]
I am unable to view the complete error, can you post the screenshot with the error details?

**Comment by imsaksham-c** [comment]
In predict function, comment the line 'image = image.cuda()' and try running the code.
The problem may have occurred because your Pytorch is not CUDA enabled.

**Comment by prasadkamble0062** [comment]
Yes its worked, Thank you so much for your reply. Thanks a lot for your
help brother 🙏
